name: dailyfit
description: A comprehensive fitness tracking application for mobile devices
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  
  # State Management
  provider: ^6.1.1
  riverpod: ^2.4.9
  
  # Database & Storage
  sqflite: ^2.3.0
  path: ^1.8.3
  shared_preferences: ^2.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # UI Components
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.0
  shimmer: ^3.0.0
  lottie: ^2.7.0
  
  # Navigation
  go_router: ^12.1.3
  
  # Media & Camera
  image_picker: ^1.0.7
  camera: ^0.10.5+5
  video_player: ^2.8.1
  
  # Charts & Data Visualization
  fl_chart: ^0.66.0
  syncfusion_flutter_charts: ^24.1.41
  
  # Notifications
  flutter_local_notifications: ^16.3.0
  
  # Permissions
  permission_handler: ^11.1.0
  
  # Date & Time
  intl: ^0.19.0
  
  # HTTP & API
  http: ^1.1.2
  dio: ^5.4.0
  
  # Utilities
  uuid: ^4.2.1
  crypto: ^3.0.3
  
  # Sensors & Health
  pedometer: ^3.0.0
  health: ^8.1.0
  
  # Maps & Location
  geolocator: ^10.1.0
  google_maps_flutter: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.7

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
    - assets/data/
  
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700